version: '3.8'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    volumes:
      - db-data:/etc/data
    environment:
      MYSQL_ROOT_PASSWORD: code89757
    networks:
      - server-network
    ports:
      - 3306:3306

  web-server:
    build:
      context: .
      # Correct the path to your Dockerfile
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    # Important to bind/mount your codebase dir to /app dir for live reload
    volumes:
      - web-data:/app
    networks:
      - server-network

volumes:
  db-data: 
  web-data:

networks:
  server-network:
    driver: bridge